// Lista canónica unificada: unión de Trabajos (18), ParteDiario (13) y Maquinaria (13)
export const TIPOS_TRABAJO: string[] = [
  'Laboreo',
  'Siembra',
  'Transplante',
  'Plantación',
  'Acolchado',
  'Encamado plástico',
  'Colocación plástico',
  'Retirada plástico',
  'Riego',
  'Abonado',
  'Tratamiento fitosanitario',
  'Preparación terreno',
  'Preparación suelo',
  'Labores tractor',
  'Poda',
  'Deshierbe',
  'Desbrozado',
  'Cosecha',
  'Recolección',
  'Transporte',
  'Limpieza nave',
  'Mantenimiento',
  'Mantenimiento maquinaria',
  'Inspección',
  'Otro',
];
